name: 'Workflow Webhook Action'
description: 'A Github workflow action to call a webhook with payload data from the originating GitHub event. Support for JSON or URL encoded endpoints.'
inputs:
  webhook_url:
    description: 'The HTTP URI of the webhook endpoint to invoke'
    required: true
  webhook_secret:
    description: 'The secret with which a signature hash is generated'
    required: true
  webhook_auth:
    description: 'Credentials to be used for BASIC authentication (optional)'
  webhook_type: 'json | form-urlencoded | json-extended'
  data:
    description: 'Optional additional data to include in the payload'
    
runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'terminal'
  color: 'gray-dark'