name: 'Workflow Webhook Action'
description: 'A Github workflow action to call a remote webhook'
inputs:
  webhook_url:
    description: 'The HTTP URI of the webhook endpoint to invoke'
    required: true
  webhook_secret:
    description: 'The secret with which to generate the signature hash'
    required: true
  webhook_auth:
    description: 'Credentials to be used for BASIC authentication'
  data:
    description: 'Who to greet'
    default: 'json'
    
runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'terminal'
  color: 'gray-dark'